from pathlib import Path
import re

import pandas as pd


# =========================================================
# PATHS
# =========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[3]

CATALOGUE_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "lof_metric_catalogue.csv"
)

OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "lof_v01_metric_manifest.csv"
)


# =========================================================
# V0.1 IMPLEMENTATION SELECTION
#
# IMPORTANT:
# These are official LOF metric names.
#
# We do NOT create new CivicData metric IDs here.
# Each name must resolve to exactly one existing metric_id
# generated by build_lof_catalogue.py.
# =========================================================

V01_METRICS = [

    # -----------------------------------------------------
    # 01 — INDICES OF DEPRIVATION
    # Already substantially implemented
    # -----------------------------------------------------

    {
        "metric_name":
            "Indices of Multiple Deprivation (IMD) average score",
        "implementation_batch": "01_iod",
        "implementation_status": "existing",
        "data_provider": "MHCLG",
        "data_collection": "English Indices of Deprivation 2025",
        "existing_civicdata_source":
            "IoD 2025 File 10 official LAD summaries",
    },

    {
        "metric_name":
            "Income deprivation affecting children index",
        "implementation_batch": "01_iod",
        "implementation_status": "existing",
        "data_provider": "MHCLG",
        "data_collection": "English Indices of Deprivation 2025",
        "existing_civicdata_source":
            "IoD 2025 File 10 official LAD summaries",
    },

    {
        "metric_name":
            "Income deprivation affecting older people index",
        "implementation_batch": "01_iod",
        "implementation_status": "existing",
        "data_provider": "MHCLG",
        "data_collection": "English Indices of Deprivation 2025",
        "existing_civicdata_source":
            "IoD 2025 File 10 official LAD summaries",
    },

    # -----------------------------------------------------
    # 02 — HEALTH / FINGERTIPS
    # -----------------------------------------------------

    {
        "metric_name":
            "Health life expectancy at birth "
            "(split by male and female)",
        "implementation_batch": "02_fingertips",
        "implementation_status": "planned",
        "data_provider": "DHSC",
        "data_collection": "Fingertips",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Smoking: percentage of those setting a quit date "
            "who successfully quit smoking",
        "implementation_batch": "02_fingertips",
        "implementation_status": "planned",
        "data_provider": "DHSC",
        "data_collection": "Fingertips Smoking Profile",
        "existing_civicdata_source": None,
    },

   {
    "metric_name":
        "Child health: percentage achieving good level of "
        "development at 2-2.5 year review ( DHSC )",
    "implementation_batch": "02_fingertips",
    "implementation_status": "planned",
    "data_provider": "DHSC",
    "data_collection": "Fingertips",
    "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Drugs and alcohol: rate of alcohol-specific mortality "
            "(directly standardised rate per 100,000)",
        "implementation_batch": "02_fingertips",
        "implementation_status": "planned",
        "data_provider": "DHSC",
        "data_collection": "Fingertips",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Mental Health: Suicide Rate",
        "implementation_batch": "02_fingertips",
        "implementation_status": "planned",
        "data_provider": "DHSC",
        "data_collection": "Fingertips",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Cardiovascular disease prevention: Proportion of NHS "
            "health checks completed across the eligible population",
        "implementation_batch": "02_fingertips",
        "implementation_status": "planned",
        "data_provider": "DHSC",
        "data_collection": "Fingertips",
        "existing_civicdata_source": None,
    },

    # -----------------------------------------------------
    # 03 — CHILDREN / EDUCATION
    # -----------------------------------------------------

    {
        "metric_name":
            "Child development: Percentage of children with a good "
            "level of development at 5 years old",
        "implementation_batch": "03_children",
        "implementation_status": "planned",
        "data_provider": "DfE",
        "data_collection": "Explore Education Statistics",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Child development: Percentage point difference between "
            "the proportion of children eligible or not eligible for "
            "Free School Meals achieving a Good Level of Development",
        "implementation_batch": "03_children",
        "implementation_status": "planned",
        "data_provider": "DfE",
        "data_collection": "Explore Education Statistics",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "School attainment: Percentage of pupils meeting the "
            "expected standard in reading, writing and maths at "
            "Key Stage 2 for all state funded schools, local authority "
            "maintained schools and academies",
        "implementation_batch": "03_children",
        "implementation_status": "planned",
        "data_provider": "DfE",
        "data_collection": "Explore Education Statistics",
        "existing_civicdata_source": None,
    },

    # -----------------------------------------------------
    # 04 — TRANSPORT
    # -----------------------------------------------------

    {
        "metric_name":
            "Passenger journeys on local bus services per head by "
            "local authority (including disaggregation by "
            "concessionary pass journeys)",
        "implementation_batch": "04_transport",
        "implementation_status": "planned",
        "data_provider": "DfT",
        "data_collection": "Local bus statistics",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Killed or seriously injured per billion vehicle miles",
        "implementation_batch": "04_transport",
        "implementation_status": "planned",
        "data_provider": "DfT",
        "data_collection": "Road safety statistics",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Public EVSEs (Electric Vehicle Supply Equipment per "
            "100,000 population)",
        "implementation_batch": "04_transport",
        "implementation_status": "planned",
        "data_provider": "DfT",
        "data_collection":
            "Electric vehicle charging infrastructure statistics",
        "existing_civicdata_source": None,
    },

    # -----------------------------------------------------
    # 05 — ECONOMIC / BUSINESS DEMOGRAPHY
    # -----------------------------------------------------

    {
        "metric_name":
            "Births of new enterprises",
        "implementation_batch": "05_business",
        "implementation_status": "planned",
        "data_provider": "ONS",
        "data_collection": "Business Demography",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Deaths of enterprises",
        "implementation_batch": "05_business",
        "implementation_status": "planned",
        "data_provider": "ONS",
        "data_collection": "Business Demography",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Business survival rate",
        "implementation_batch": "05_business",
        "implementation_status": "planned",
        "data_provider": "ONS",
        "data_collection": "Business Demography",
        "existing_civicdata_source": None,
    },

    # -----------------------------------------------------
    # 06 — ENVIRONMENT / NEIGHBOURHOODS
    # -----------------------------------------------------

    {
        "metric_name":
            "Percentage of total household waste sent for recycling, "
            "compost and reuse",
        "implementation_batch": "06_environment",
        "implementation_status": "planned",
        "data_provider": "Defra",
        "data_collection":
            "Local authority collected waste statistics",
        "existing_civicdata_source": None,
    },

    {
        "metric_name":
            "Rate of fly-tipping enforcement actions per incident",
        "implementation_batch": "06_environment",
        "implementation_status": "planned",
        "data_provider": "Defra",
        "data_collection": "Fly-tipping statistics",
        "existing_civicdata_source": None,
    },
]


# =========================================================
# NORMALISATION
# =========================================================

def normalise_metric_name(value):
    """
    Normalise harmless typography differences while retaining
    the requirement for a deterministic full-name match.

    This does NOT perform fuzzy matching.
    """

    if pd.isna(value):
        return ""

    value = str(value).strip()

    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u00a0": " ",
    }

    for old, new in replacements.items():
        value = value.replace(old, new)

    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    return value.casefold().strip()


# =========================================================
# LOAD CATALOGUE
# =========================================================

def load_catalogue():
    """
    Load the official MHCLG-derived CivicData LOF catalogue.
    """

    if not CATALOGUE_PATH.exists():
        raise FileNotFoundError(
            "LOF catalogue not found:\n"
            f"{CATALOGUE_PATH}\n\n"
            "Run build_lof_catalogue.py first."
        )

    catalogue = pd.read_csv(
        CATALOGUE_PATH
    )

    required_columns = [
        "metric_id",
        "metric_name",
        "outcome_id",
        "outcome_name",
        "metric_type",
        "metric_status",
        "source_organisation",
        "source_dataset",
        "source_url",
    ]

    missing = [
        column
        for column in required_columns
        if column not in catalogue.columns
    ]

    if missing:
        raise ValueError(
            "Catalogue is missing required columns:\n"
            f"{missing}"
        )

    print(
        f"Catalogue relationships: "
        f"{len(catalogue):,}"
    )

    print(
        f"Unique catalogue metrics: "
        f"{catalogue['metric_id'].nunique():,}"
    )

    return catalogue


# =========================================================
# BUILD UNIQUE METRIC VIEW
# =========================================================

def build_unique_metric_view(catalogue):
    """
    Produce one record per official metric.

    The master catalogue remains relationship-level because
    one metric may belong to multiple LOF outcomes.
    """

    columns = [
        "metric_id",
        "metric_name",
        "metric_status",
        "source_organisation",
        "source_dataset",
        "source_url",
    ]

    unique_metrics = (
        catalogue[columns]
        .drop_duplicates(
            subset=["metric_id"]
        )
        .copy()
    )

    unique_metrics[
        "_normalised_metric_name"
    ] = unique_metrics[
        "metric_name"
    ].map(
        normalise_metric_name
    )

    return unique_metrics


# =========================================================
# RESOLVE EXACT OFFICIAL METRICS
# =========================================================

def resolve_selections(catalogue):
    """
    Resolve each v0.1 official metric name to exactly one
    existing CivicData metric_id.

    No fuzzy selection and no fallback guessing are allowed.
    """

    unique_metrics = build_unique_metric_view(
        catalogue
    )

    selected = []

    failures = []

    print(
        "\n=== RESOLVING OFFICIAL V0.1 METRICS ==="
    )

    for number, specification in enumerate(
        V01_METRICS,
        start=1,
    ):
        requested_name = specification[
            "metric_name"
        ]

        normalised_requested = (
            normalise_metric_name(
                requested_name
            )
        )

        matches = unique_metrics[
            unique_metrics[
                "_normalised_metric_name"
            ].eq(
                normalised_requested
            )
        ].copy()

        if len(matches) == 1:
            match = matches.iloc[0]

            if (
                normalise_metric_name(
                    match["metric_status"]
                )
                != "available"
            ):
                failures.append(
                    {
                        "selection": number,
                        "requested_name":
                            requested_name,
                        "problem":
                            "metric is not marked available",
                    }
                )

                print(
                    f"{number:02d}. FAIL "
                    f"{requested_name}"
                )

                continue

            selected.append(
                {
                    "metric_id":
                        match["metric_id"],
                    "implementation_batch":
                        specification[
                            "implementation_batch"
                        ],
                    "implementation_status":
                        specification[
                            "implementation_status"
                        ],
                    "data_provider":
                        specification[
                            "data_provider"
                        ],
                    "data_collection":
                        specification[
                            "data_collection"
                        ],
                    "existing_civicdata_source":
                        specification[
                            "existing_civicdata_source"
                        ],
                }
            )

            print(
                f"{number:02d}. PASS "
                f"{match['metric_id']} "
                f"{match['metric_name']}"
            )

        elif len(matches) == 0:
            failures.append(
                {
                    "selection": number,
                    "requested_name":
                        requested_name,
                    "problem":
                        "no exact catalogue match",
                }
            )

            print(
                f"{number:02d}. FAIL "
                f"{requested_name}"
            )

        else:
            failures.append(
                {
                    "selection": number,
                    "requested_name":
                        requested_name,
                    "problem":
                        "multiple exact matches",
                }
            )

            print(
                f"{number:02d}. FAIL "
                f"{requested_name}"
            )

    if failures:
        print(
            "\n=== SELECTION FAILURES ==="
        )

        failure_df = pd.DataFrame(
            failures
        )

        print(
            failure_df.to_string(
                index=False
            )
        )

        print(
            "\nThe builder has stopped without "
            "creating a manifest."
        )

        print(
            "This protects CivicData from silently "
            "mapping a LOF metric incorrectly."
        )

        raise ValueError(
            f"{len(failures)} v0.1 metric "
            "selection(s) require review."
        )

    selections = pd.DataFrame(
        selected
    )

    if selections[
        "metric_id"
    ].duplicated().any():
        duplicates = selections[
            selections[
                "metric_id"
            ].duplicated(
                keep=False
            )
        ]

        raise ValueError(
            "A LOF metric has been selected "
            "more than once:\n"
            f"{duplicates}"
        )

    return selections


# =========================================================
# BUILD RELATIONSHIP-LEVEL MANIFEST
# =========================================================

def build_manifest(
    catalogue,
    selections,
):
    """
    Preserve all official outcome relationships.

    A single implemented observation may therefore support
    more than one LOF outcome without downloading the same
    observation twice.
    """

    official_columns = [
        "metric_id",
        "metric_name",
        "outcome_id",
        "outcome_name",
        "metric_type",
        "metric_status",
        "source_organisation",
        "source_dataset",
        "source_url",
    ]

    manifest = (
        catalogue[
            official_columns
        ]
        .merge(
            selections,
            on="metric_id",
            how="inner",
            validate="many_to_one",
        )
    )

    manifest = manifest[
        [
            "metric_id",
            "metric_name",
            "outcome_id",
            "outcome_name",
            "metric_type",
            "metric_status",
            "source_organisation",
            "source_dataset",
            "source_url",
            "data_provider",
            "data_collection",
            "implementation_batch",
            "implementation_status",
            "existing_civicdata_source",
        ]
    ].copy()

    manifest = manifest.sort_values(
        [
            "implementation_batch",
            "outcome_id",
            "metric_name",
        ]
    ).reset_index(
        drop=True
    )

    return manifest


# =========================================================
# VALIDATION
# =========================================================

def validate_manifest(
    manifest,
    selections,
):
    """
    Validate structural integrity of the implementation
    manifest.
    """

    print(
        "\n=== MANIFEST VALIDATION ==="
    )

    expected_unique = len(
        V01_METRICS
    )

    selected_unique = selections[
        "metric_id"
    ].nunique()

    manifest_unique = manifest[
        "metric_id"
    ].nunique()

    print(
        f"Expected unique metrics: "
        f"{expected_unique}"
    )

    print(
        f"Resolved unique metrics: "
        f"{selected_unique}"
    )

    print(
        f"Manifest unique metrics: "
        f"{manifest_unique}"
    )

    print(
        f"Outcome-metric relationships: "
        f"{len(manifest)}"
    )

    print(
        f"LOF outcomes represented: "
        f"{manifest['outcome_id'].nunique()}"
    )

    if selected_unique != expected_unique:
        raise ValueError(
            "Resolved metric count does not "
            "equal v0.1 specification count."
        )

    if manifest_unique != expected_unique:
        raise ValueError(
            "Manifest unique metric count does "
            "not equal v0.1 specification count."
        )

    duplicate_relationships = (
        manifest.duplicated(
            subset=[
                "metric_id",
                "outcome_id",
            ]
        ).sum()
    )

    print(
        f"Duplicate outcome-metric relationships: "
        f"{duplicate_relationships}"
    )

    if duplicate_relationships:
        raise ValueError(
            "Duplicate outcome-metric "
            "relationships detected."
        )

    placeholder_count = (
        manifest[
            "metric_status"
        ]
        .map(
            normalise_metric_name
        )
        .ne("available")
        .sum()
    )

    print(
        f"Unavailable/placeholder rows: "
        f"{placeholder_count}"
    )

    if placeholder_count:
        raise ValueError(
            "Manifest contains unavailable "
            "or placeholder metrics."
        )

    print(
        "\nMetrics by implementation batch:"
    )

    batch_counts = (
        manifest[
            [
                "metric_id",
                "implementation_batch",
            ]
        ]
        .drop_duplicates()
        ["implementation_batch"]
        .value_counts()
        .sort_index()
    )

    for batch, count in (
        batch_counts.items()
    ):
        print(
            f"  {batch}: {count}"
        )

    print(
        "\nImplementation status:"
    )

    status_counts = (
        manifest[
            [
                "metric_id",
                "implementation_status",
            ]
        ]
        .drop_duplicates()
        ["implementation_status"]
        .value_counts()
    )

    for status, count in (
        status_counts.items()
    ):
        print(
            f"  {status}: {count}"
        )

    print(
        "\nManifest validation PASS"
    )


# =========================================================
# SAVE
# =========================================================

def save_manifest(manifest):
    """
    Save only after every validation has passed.
    """

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    manifest.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    print(
        "\nManifest saved:"
    )

    print(
        OUTPUT_PATH
    )


# =========================================================
# REPORT
# =========================================================

def show_selected_metrics(manifest):
    """
    Display one record per implemented/planned metric.
    """

    unique = (
        manifest[
            [
                "metric_id",
                "metric_name",
                "data_provider",
                "data_collection",
                "implementation_batch",
                "implementation_status",
            ]
        ]
        .drop_duplicates(
            subset=[
                "metric_id"
            ]
        )
        .sort_values(
            [
                "implementation_batch",
                "metric_name",
            ]
        )
    )

    print(
        "\n=== CIVICDATA LOF V0.1 METRICS ==="
    )

    print(
        unique.to_string(
            index=False
        )
    )


def show_cross_outcome_metrics(
    manifest,
):
    """
    Report selected metrics appearing under more than one
    official LOF outcome.
    """

    counts = (
        manifest.groupby(
            [
                "metric_id",
                "metric_name",
            ]
        )[
            "outcome_id"
        ]
        .nunique()
        .reset_index(
            name="outcome_count"
        )
    )

    cross_outcome = counts[
        counts[
            "outcome_count"
        ] > 1
    ]

    print(
        "\n=== CROSS-OUTCOME METRICS ==="
    )

    if cross_outcome.empty:
        print(
            "None in current v0.1 selection."
        )

        return

    for _, metric in (
        cross_outcome.iterrows()
    ):
        print(
            f"\n{metric['metric_name']}"
        )

        relationships = (
            manifest[
                manifest[
                    "metric_id"
                ].eq(
                    metric[
                        "metric_id"
                    ]
                )
            ][
                [
                    "outcome_id",
                    "outcome_name",
                ]
            ]
            .drop_duplicates()
            .sort_values(
                "outcome_id"
            )
        )

        for _, relationship in (
            relationships.iterrows()
        ):
            print(
                f"  "
                f"{int(relationship['outcome_id']):02d} "
                f"{relationship['outcome_name']}"
            )


# =========================================================
# MAIN
# =========================================================

def main():
    print(
        "\n========================================"
    )

    print(
        "CIVICDATA LOF V0.1 IMPLEMENTATION "
        "MANIFEST"
    )

    print(
        "========================================"
    )

    catalogue = load_catalogue()

    selections = resolve_selections(
        catalogue
    )

    manifest = build_manifest(
        catalogue,
        selections,
    )

    validate_manifest(
        manifest,
        selections,
    )

    save_manifest(
        manifest
    )

    show_selected_metrics(
        manifest
    )

    show_cross_outcome_metrics(
        manifest
    )

    print(
        "\n=== COMPLETE ==="
    )

    print(
        "The CivicData LOF v0.1 manifest "
        "has been built from existing official "
        "catalogue metrics."
    )

    print(
        "No LOF metrics or statistical-neighbour "
        "relationships were created or inferred "
        "by CivicData."
    )


if __name__ == "__main__":
    main()